name: Build and Push Images

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Set Git Tag or Commit SHA
        run: |
            if [[ "$GITHUB_REF" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
                echo "GIT_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
            else
                calculatedSha=$(git rev-parse --short ${{ github.sha }})
                echo "GIT_TAG=$calculatedSha" >> $GITHUB_ENV
            fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
          files: |
            ./docker-bake.hcl
          set: |
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
            VITE_API_BASE_URL: ${{ env.VITE_API_BASE_URL }}
            VITE_COUNTRY_API_URL: ${{ env.VITE_COUNTRY_API_URL }}
            VERSION: ${{ env.GIT_TAG }}